import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { after, describe, it } from "node:test";
import { GENERATED_MARKER } from "../config.js";
import {
  destLabel,
  ideInstallRoots,
  isNhxGenerated,
  syncAdapters,
} from "./cursor.js";

const tmpDirs: string[] = [];

function tmp(): string {
  const d = fs.mkdtempSync(path.join(os.tmpdir(), "nhx-adapter-"));
  tmpDirs.push(d);
  return d;
}

function seedNhx(cwd: string): void {
  const cmd = path.join(cwd, ".nhx", "commands");
  const skill = path.join(cwd, ".nhx", "skills", "demo-skill");
  fs.mkdirSync(cmd, { recursive: true });
  fs.mkdirSync(skill, { recursive: true });
  fs.writeFileSync(path.join(cmd, "nhx-req-prd.md"), "# /nhx-req-prd\n\ndo the thing\n", "utf8");
  fs.writeFileSync(path.join(skill, "SKILL.md"), "# demo skill\n", "utf8");
}

after(() => {
  for (const d of tmpDirs) {
    fs.rmSync(d, { recursive: true, force: true });
  }
});

describe("ideInstallRoots / destLabel", () => {
  it("project roots are under cwd", () => {
    const cwd = "/tmp/proj";
    const home = "/tmp/home";
    const r = ideInstallRoots("project", cwd, home);
    assert.equal(r.cursorSkills, path.join(cwd, ".cursor", "skills"));
    assert.equal(r.cursorCommands, path.join(cwd, ".cursor", "commands"));
    assert.equal(r.traeSkills, path.join(cwd, ".trae", "skills"));
  });

  it("global roots are under homedir", () => {
    const cwd = "/tmp/proj";
    const home = "/tmp/home";
    const r = ideInstallRoots("global", cwd, home);
    assert.equal(r.cursorSkills, path.join(home, ".cursor", "skills"));
    assert.equal(r.cursorCommands, path.join(home, ".cursor", "commands"));
    assert.equal(r.traeSkills, path.join(home, ".trae", "skills"));
  });

  it("trae-cn roots use .trae-cn", () => {
    const cwd = "/tmp/proj";
    const home = "/tmp/home";
    assert.equal(
      ideInstallRoots("global", cwd, home, ".trae-cn").traeSkills,
      path.join(home, ".trae-cn", "skills"),
    );
    assert.equal(
      ideInstallRoots("project", cwd, home, ".trae-cn").traeSkills,
      path.join(cwd, ".trae-cn", "skills"),
    );
  });

  it("destLabel prefixes ~ for global", () => {
    assert.equal(destLabel("project", ".cursor/skills/x/SKILL.md"), ".cursor/skills/x/SKILL.md");
    assert.equal(destLabel("global", ".cursor/skills/x/SKILL.md"), "~/.cursor/skills/x/SKILL.md");
  });
});

describe("syncAdapters project vs global", () => {
  it("default project scope writes cwd .cursor/.trae and not homedir", () => {
    const cwd = tmp();
    const home = tmp();
    seedNhx(cwd);
    const out = syncAdapters(["cursor", "trae"], cwd, { scope: "project", home });
    const cursor = out.cursor as { skills: number; commands: number; scope: string };
    const trae = out.trae as { skills: number; scope: string };
    assert.equal(cursor.scope, "project");
    assert.equal(cursor.commands, 1);
    assert.equal(cursor.skills, 1);
    assert.equal(trae.skills, 2); // command shell + demo-skill

    const projSkill = path.join(cwd, ".cursor", "skills", "demo-skill", "SKILL.md");
    const projCmd = path.join(cwd, ".cursor", "commands", "nhx-req-prd.md");
    const traeSkill = path.join(cwd, ".trae", "skills", "demo-skill", "SKILL.md");
    assert.equal(fs.existsSync(projSkill), true);
    assert.equal(fs.existsSync(projCmd), true);
    assert.equal(fs.existsSync(traeSkill), true);
    assert.doesNotMatch(fs.readFileSync(projSkill, "utf8"), /GENERATED by nhx adapter/);
    assert.doesNotMatch(fs.readFileSync(traeSkill, "utf8"), /GENERATED by nhx adapter/);
    assert.match(fs.readFileSync(projCmd, "utf8"), /GENERATED by nhx adapter/);

    assert.equal(fs.existsSync(path.join(home, ".cursor", "skills", "demo-skill", "SKILL.md")), false);
    assert.equal(fs.existsSync(path.join(home, ".trae", "skills", "demo-skill", "SKILL.md")), false);
  });

  it("global scope writes homedir and does not create project skills/commands", () => {
    const cwd = tmp();
    const home = tmp();
    seedNhx(cwd);
    syncAdapters(["cursor", "trae"], cwd, { scope: "global", home });

    const homeSkill = path.join(home, ".cursor", "skills", "demo-skill", "SKILL.md");
    const homeCmd = path.join(home, ".cursor", "commands", "nhx-req-prd.md");
    const homeTrae = path.join(home, ".trae", "skills", "demo-skill", "SKILL.md");
    assert.equal(fs.existsSync(homeSkill), true);
    assert.equal(fs.existsSync(homeCmd), true);
    assert.equal(fs.existsSync(homeTrae), true);
    assert.doesNotMatch(fs.readFileSync(homeSkill, "utf8"), /GENERATED by nhx adapter/);
    assert.doesNotMatch(fs.readFileSync(homeTrae, "utf8"), /GENERATED by nhx adapter/);
    assert.match(fs.readFileSync(homeCmd, "utf8"), /GENERATED by nhx adapter/);

    assert.equal(fs.existsSync(path.join(cwd, ".cursor", "skills")), false);
    assert.equal(fs.existsSync(path.join(cwd, ".cursor", "commands")), false);
    assert.equal(fs.existsSync(path.join(cwd, ".trae", "skills")), false);

    // hooks stay project-local (Cursor + Trae)
    assert.equal(fs.existsSync(path.join(cwd, ".cursor", "hooks.json")), true);
    assert.equal(fs.existsSync(path.join(cwd, ".trae", "hooks.json")), true);
    assert.equal(fs.existsSync(path.join(cwd, ".trae", "skills")), false);
  });

  it("only removes nhx-generated skill dirs in the active dest", () => {
    const cwd = tmp();
    const home = tmp();
    seedNhx(cwd);
    const skillDest = path.join(cwd, ".cursor", "skills");
    fs.mkdirSync(path.join(skillDest, "user-own"), { recursive: true });
    fs.writeFileSync(path.join(skillDest, "user-own", "SKILL.md"), "# mine\n", "utf8");
    fs.mkdirSync(path.join(skillDest, "stale-nhx"), { recursive: true });
    fs.writeFileSync(
      path.join(skillDest, "stale-nhx", "SKILL.md"),
      `<!-- ${GENERATED_MARKER} .cursor/skills/stale-nhx/SKILL.md (hash:abc) -->\n# old\n`,
      "utf8",
    );

    syncAdapters(["cursor"], cwd, { scope: "project", home });

    assert.equal(fs.existsSync(path.join(skillDest, "user-own", "SKILL.md")), true);
    assert.equal(fs.existsSync(path.join(skillDest, "stale-nhx")), false);
    assert.equal(isNhxGenerated(path.join(skillDest, "demo-skill", "SKILL.md")), false);
    assert.doesNotMatch(fs.readFileSync(path.join(skillDest, "demo-skill", "SKILL.md"), "utf8"), /GENERATED/);
  });

  it("trae-cn global writes ~/.trae-cn/skills and not ~/.trae/skills", () => {
    const cwd = tmp();
    const home = tmp();
    seedNhx(cwd);
    const out = syncAdapters(["trae-cn"], cwd, { scope: "global", home });
    const result = out["trae-cn"] as { skills: number; dest: string; traeDir: string };
    assert.equal(result.traeDir, ".trae-cn");
    assert.equal(result.skills, 2);
    assert.equal(result.dest, path.join(home, ".trae-cn", "skills"));

    const skill = path.join(home, ".trae-cn", "skills", "demo-skill", "SKILL.md");
    assert.equal(fs.existsSync(skill), true);
    assert.equal(fs.readFileSync(skill, "utf8"), "# demo skill\n");
    assert.doesNotMatch(fs.readFileSync(skill, "utf8"), /GENERATED by nhx adapter/);
    assert.equal(fs.existsSync(path.join(home, ".trae", "skills")), false);
    assert.equal(fs.existsSync(path.join(cwd, ".trae-cn", "skills")), false);
    // Trae-CN still writes project-local .trae/hooks.json with --ide trae-cn
    const prompt = fs.readFileSync(path.join(cwd, ".trae", "hooks", "nhx-trae-prompt.mjs"), "utf8");
    assert.match(prompt, /"--ide", "trae-cn"/);
    assert.equal(fs.existsSync(path.join(home, ".trae-cn", "hooks.json")), true);
    assert.match(
      fs.readFileSync(path.join(home, ".trae-cn", "hooks.json"), "utf8"),
      /nhx-trae-prompt\.mjs/,
    );
  });
});

describe("trae hooks", () => {
  it("writes Trae hooks.json events and scripts on adapter sync", () => {
    const cwd = tmp();
    const home = tmp();
    seedNhx(cwd);
    const out = syncAdapters(["trae"], cwd, { scope: "project", home });
    const trae = out.trae as { hooks: { hooksJson: boolean; scripts: string[]; ide: string } };
    assert.equal(trae.hooks.hooksJson, true);
    assert.equal(trae.hooks.ide, "trae");
    assert.deepEqual(trae.hooks.scripts, [
      "nhx-trae-prompt.mjs",
      "nhx-trae-stop.mjs",
      "nhx-trae-post-tool.mjs",
    ]);

    const hooksPath = path.join(cwd, ".trae", "hooks.json");
    assert.equal(fs.existsSync(hooksPath), true);
    const doc = JSON.parse(fs.readFileSync(hooksPath, "utf8"));
    assert.ok(Array.isArray(doc.hooks.UserPromptSubmit));
    assert.ok(Array.isArray(doc.hooks.Stop));
    assert.ok(Array.isArray(doc.hooks.PostToolUse));
    assert.equal(doc.hooks.Stop[0].loop_limit, 3);
    assert.equal(doc.hooks.PostToolUse[0].matcher, "Skill|Edit|Write");
    assert.match(doc.hooks.UserPromptSubmit[0].hooks[0].command, /nhx-trae-prompt\.mjs/);
    assert.equal(doc.hooks.SessionStart, undefined);

    for (const name of trae.hooks.scripts) {
      assert.equal(fs.existsSync(path.join(cwd, ".trae", "hooks", name)), true);
    }
    const prompt = fs.readFileSync(path.join(cwd, ".trae", "hooks", "nhx-trae-prompt.mjs"), "utf8");
    assert.match(prompt, /"--ide", "trae"/);
    assert.equal(fs.existsSync(path.join(home, ".trae", "hooks.json")), true);
  });

  it("preserves user hook groups and does not duplicate nhx groups on resync", () => {
    const cwd = tmp();
    const home = tmp();
    seedNhx(cwd);
    const hooksPath = path.join(cwd, ".trae", "hooks.json");
    fs.mkdirSync(path.dirname(hooksPath), { recursive: true });
    fs.writeFileSync(
      hooksPath,
      JSON.stringify(
        {
          version: 1,
          hooks: {
            UserPromptSubmit: [
              {
                hooks: [{ type: "command", command: "echo user-own-hook" }],
              },
            ],
          },
        },
        null,
        2,
      ),
      "utf8",
    );

    syncAdapters(["trae"], cwd, { scope: "project", home });
    syncAdapters(["trae"], cwd, { scope: "project", home });

    const doc = JSON.parse(fs.readFileSync(hooksPath, "utf8"));
    const groups = doc.hooks.UserPromptSubmit;
    assert.equal(groups.length, 2);
    assert.equal(groups[0].hooks[0].command, "echo user-own-hook");
    assert.match(groups[1].hooks[0].command, /nhx-trae-prompt\.mjs/);
    assert.equal(doc.hooks.Stop.length, 1);
    assert.equal(doc.hooks.PostToolUse.length, 1);
  });
});
