import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { after, describe, it } from "node:test";
import { qoderHomeDir, syncQoderHooks } from "./qoder-hooks.js";

const tmpDirs: string[] = [];

function tmp(): string {
  const d = fs.mkdtempSync(path.join(os.tmpdir(), "nhx-qoder-hooks-"));
  tmpDirs.push(d);
  return d;
}

after(() => {
  for (const d of tmpDirs) fs.rmSync(d, { recursive: true, force: true });
});

describe("qoderHomeDir", () => {
  it("defaults to ~/.qoder", () => {
    const home = "/tmp/home";
    assert.equal(qoderHomeDir(home, {}), path.join(home, ".qoder"));
  });

  it("respects QODER_CONFIG_DIR", () => {
    const override = tmp();
    assert.equal(qoderHomeDir("/tmp/home", { QODER_CONFIG_DIR: override }), path.resolve(override));
  });
});

describe("qoder hooks sync", () => {
  it("writes project settings and scripts", () => {
    const cwd = tmp();
    const home = tmp();
    const out = syncQoderHooks(cwd, home, "project", {});
    assert.equal(out.settingsJson, true);
    assert.equal(out.ide, "qoder");
    assert.equal(fs.existsSync(path.join(cwd, ".qoder", "settings.json")), true);
    const settings = JSON.parse(fs.readFileSync(path.join(cwd, ".qoder", "settings.json"), "utf8"));
    assert.ok(Array.isArray(settings.hooks.UserPromptSubmit));
    assert.ok(Array.isArray(settings.hooks.Stop));
    assert.ok(Array.isArray(settings.hooks.PostToolUse));
    assert.equal(settings.hooks.PostToolUse[0].matcher, "Skill|Edit|Write");
    assert.equal(settings._nhx.ide, "qoder");
    const prompt = fs.readFileSync(path.join(cwd, ".qoder", "hooks", "nhx-qoder-prompt.mjs"), "utf8");
    assert.match(prompt, /"--ide", "qoder"/);
  });

  it("keeps user hooks and dedupes nhx hooks on resync", () => {
    const cwd = tmp();
    const home = tmp();
    const settingsPath = path.join(cwd, ".qoder", "settings.json");
    fs.mkdirSync(path.dirname(settingsPath), { recursive: true });
    fs.writeFileSync(
      settingsPath,
      JSON.stringify(
        {
          hooks: {
            UserPromptSubmit: [{ hooks: [{ type: "command", command: "echo user-hook" }] }],
          },
        },
        null,
        2,
      ),
      "utf8",
    );
    syncQoderHooks(cwd, home, "project", {});
    syncQoderHooks(cwd, home, "project", {});
    const settings = JSON.parse(fs.readFileSync(settingsPath, "utf8"));
    assert.equal(settings.hooks.UserPromptSubmit.length, 2);
    assert.equal(settings.hooks.UserPromptSubmit[0].hooks[0].command, "echo user-hook");
    assert.equal(settings.hooks.Stop.length, 1);
    assert.equal(settings.hooks.PostToolUse.length, 1);
  });

  it("global scope writes global settings and strips project nhx hooks", () => {
    const cwd = tmp();
    const home = tmp();
    syncQoderHooks(cwd, home, "project", {});
    assert.match(
      fs.readFileSync(path.join(cwd, ".qoder", "settings.json"), "utf8"),
      /nhx-qoder-prompt/,
    );
    syncQoderHooks(cwd, home, "global", {});
    const globalSettings = path.join(home, ".qoder", "settings.json");
    assert.equal(fs.existsSync(globalSettings), true);
    assert.match(fs.readFileSync(globalSettings, "utf8"), /nhx-qoder-prompt/);
    const projectDoc = JSON.parse(fs.readFileSync(path.join(cwd, ".qoder", "settings.json"), "utf8"));
    const events = Object.values(projectDoc.hooks || {}).flat() as unknown[];
    assert.equal(events.some((g) => JSON.stringify(g).includes("nhx-qoder")), false);
  });

  it("strips nhx hooks from settings.local.json", () => {
    const cwd = tmp();
    const home = tmp();
    const localPath = path.join(cwd, ".qoder", "settings.local.json");
    fs.mkdirSync(path.dirname(localPath), { recursive: true });
    fs.writeFileSync(
      localPath,
      JSON.stringify(
        {
          hooks: {
            UserPromptSubmit: [
              { hooks: [{ type: "command", command: "node .qoder/hooks/nhx-qoder-prompt.mjs" }] },
            ],
          },
          _nhx: { generated: "GENERATED by nhx adapter", ide: "qoder" },
        },
        null,
        2,
      ),
      "utf8",
    );
    syncQoderHooks(cwd, home, "project", {});
    const local = JSON.parse(fs.readFileSync(localPath, "utf8"));
    const events = Object.values(local.hooks || {}).flat() as unknown[];
    assert.equal(events.some((g) => JSON.stringify(g).includes("nhx-qoder")), false);
    assert.equal(local._nhx, undefined);
  });

  it("global uses QODER_CONFIG_DIR when set", () => {
    const cwd = tmp();
    const home = tmp();
    const configDir = tmp();
    const out = syncQoderHooks(cwd, home, "global", { QODER_CONFIG_DIR: configDir });
    assert.equal(out.globalDest, path.join(path.resolve(configDir), "settings.json"));
    assert.equal(fs.existsSync(path.join(configDir, "settings.json")), true);
    assert.equal(fs.existsSync(path.join(configDir, "hooks", "nhx-qoder-prompt.mjs")), true);
    assert.equal(fs.existsSync(path.join(home, ".qoder", "settings.json")), false);
  });
});
