import fs from "node:fs";
import path from "node:path";
import yaml from "yaml";

export const NHX_DIR = ".nhx";
export const DEFAULT_API = "http://127.0.0.1:8000";
export const GENERATED_MARKER = "GENERATED by nhx adapter";

export type InstallScope = "project" | "global";

export type NhxConfig = {
  api_base: string;
  project_id?: number;
  project_slug?: string;
  stages: string[];
  /** IDE targets: cursor, trae, trae-cn, codebuddy, workbuddy, qoder. */
  targets: string[];
  /** IDE skill/command projection: project (.cursor/.codebuddy/.qoder) or user-global (~/.cursor/~/.codebuddy/~/.workbuddy/~/.qoder). */
  install_scope: InstallScope;
  /** Human approval status query interval (minutes). Default 120. */
  approval_check_interval_minutes?: number;
  /** Reserved for future: hourly_auto | manual_only. */
  approval_check_mode?: string;
};

export function parseInstallScope(v: unknown): InstallScope {
  return v === "global" ? "global" : "project";
}

/** CLI flags override config; default is project-local. */
export function resolveInstallScope(opts: {
  global?: boolean;
  local?: boolean;
  config?: NhxConfig | null;
}): InstallScope {
  if (opts.global && opts.local) {
    throw new Error("--global 与 --local 不能同时使用");
  }
  if (opts.global) return "global";
  if (opts.local) return "project";
  return parseInstallScope(opts.config?.install_scope);
}

export type Credentials = {
  access_token: string;
  username?: string;
  saved_at?: string;
};

export function nhxRoot(cwd = process.cwd()): string {
  return path.join(cwd, NHX_DIR);
}

export function ensureNhxDir(cwd = process.cwd()): string {
  const root = nhxRoot(cwd);
  fs.mkdirSync(root, { recursive: true });
  fs.mkdirSync(path.join(root, "guides"), { recursive: true });
  fs.mkdirSync(path.join(root, "sensors"), { recursive: true });
  fs.mkdirSync(path.join(root, "commands"), { recursive: true });
  fs.mkdirSync(path.join(root, "skills"), { recursive: true });
  return root;
}

export function configPath(cwd = process.cwd()): string {
  return path.join(nhxRoot(cwd), "config.yaml");
}

export function credentialsPath(cwd = process.cwd()): string {
  return path.join(nhxRoot(cwd), "credentials");
}

export function lockPath(cwd = process.cwd()): string {
  return path.join(nhxRoot(cwd), "lock.json");
}

export function loadConfig(cwd = process.cwd()): NhxConfig | null {
  const p = configPath(cwd);
  if (!fs.existsSync(p)) return null;
  const doc = yaml.parse(fs.readFileSync(p, "utf8")) || {};
  return {
    api_base: String(doc.api_base || DEFAULT_API),
    project_id: doc.project_id != null ? Number(doc.project_id) : undefined,
    project_slug: doc.project_slug ? String(doc.project_slug) : undefined,
    stages: Array.isArray(doc.stages) ? doc.stages.map(String) : [],
    targets: Array.isArray(doc.targets) ? doc.targets.map(String) : ["cursor", "trae"],
    install_scope: parseInstallScope(doc.install_scope),
    approval_check_interval_minutes:
      doc.approval_check_interval_minutes != null
        ? Number(doc.approval_check_interval_minutes)
        : undefined,
    approval_check_mode: doc.approval_check_mode ? String(doc.approval_check_mode) : undefined,
  };
}

export function saveConfig(cfg: NhxConfig, cwd = process.cwd()): void {
  ensureNhxDir(cwd);
  const body = yaml.stringify({
    api_base: cfg.api_base,
    project_id: cfg.project_id,
    project_slug: cfg.project_slug,
    stages: cfg.stages,
    targets: cfg.targets,
    install_scope: parseInstallScope(cfg.install_scope),
    approval_check_interval_minutes: cfg.approval_check_interval_minutes,
    approval_check_mode: cfg.approval_check_mode,
  });
  fs.writeFileSync(configPath(cwd), body, "utf8");
}

export function loadCredentials(cwd = process.cwd()): Credentials | null {
  const p = credentialsPath(cwd);
  if (!fs.existsSync(p)) return null;
  try {
    return JSON.parse(fs.readFileSync(p, "utf8")) as Credentials;
  } catch {
    return null;
  }
}

export function saveCredentials(creds: Credentials, cwd = process.cwd()): void {
  ensureNhxDir(cwd);
  fs.writeFileSync(
    credentialsPath(cwd),
    JSON.stringify({ ...creds, saved_at: new Date().toISOString() }, null, 2),
    "utf8",
  );
}

/** Resolve API base: --api > NHX_API > config > default */
export function resolveApiBase(cliApi?: string, cwd = process.cwd()): string {
  if (cliApi?.trim()) return cliApi.trim().replace(/\/$/, "");
  const env = (process.env.NHX_API || process.env.NHX_API_BASE || "").trim();
  if (env) return env.replace(/\/$/, "");
  const cfg = loadConfig(cwd);
  if (cfg?.api_base) return cfg.api_base.replace(/\/$/, "");
  return DEFAULT_API;
}

export function mergeStages(existing: string[], next: string[]): string[] {
  const out = [...existing];
  for (const s of next) {
    if (s && !out.includes(s)) out.push(s);
  }
  return out;
}
