import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { syncCheck } from "@harnessx/core/sync.js";
import { readDeliveryTrace } from "@harnessx/core/deliveryTrace.js";
import { sha256 } from "@harnessx/core/telemetry.js";
import type { Finding, SensorReport } from "@harnessx/core/schemas.js";
import type { SensorContext } from "./types.js";

const ADAPTER_HEADER_RE = /GENERATED by harnessx adapter v[\d.]+ — source: ([^\n]+) — hash:([a-f0-9]+)/;

function block(findings: Finding[], ctx: SensorContext, summary: string): SensorReport {
  return {
    sensor: ctx.def.id,
    status: findings.some((f) => f.severity === "block") ? "fail" : "pass",
    summary,
    findings,
    fix_hint: ctx.def.fix_hint,
    agent_instruction: findings.length ? "Resolve drift: align specs, design hints, and code; run hx sync for details." : undefined
  };
}

function adapterDriftFindings(root: string): Finding[] {
  const findings: Finding[] = [];
  const markers = [".cursor/rules/harnessx.mdc", "AGENTS.md", ".trae/rules/project_rules.md"];
  for (const rel of markers) {
    const abs = path.join(root, rel);
    if (!fs.existsSync(abs)) continue;
    const raw = fs.readFileSync(abs, "utf8");
    const m = raw.match(ADAPTER_HEADER_RE);
    if (!m) continue;
    const body = raw.split("\n").slice(1).join("\n");
    if (sha256(body).slice(0, 16) !== m[2]) {
      findings.push({
        severity: "warn",
        file: rel,
        rule: "adapter-drift",
        message: `${rel} was manually edited — run hx adapter sync to restore`
      });
    }
  }
  return findings;
}

/**
 * sensor.drift — unified spec↔code, design↔code, and adapter drift (v0.4).
 */
export const driftSensor = (ctx: SensorContext): SensorReport => {
  const findings: Finding[] = [];

  for (const f of syncCheck(ctx.ws)) {
    findings.push({
      severity: "warn",
      rule: "spec-code-drift",
      message: `[${f.kind}] Scenario: ${f.scenario} — ${f.suggestion.slice(0, 120)}`
    });
  }

  if (ctx.change) {
    const trace = readDeliveryTrace(ctx.ws, ctx.change);
    for (const [key, entry] of Object.entries(trace.requirements)) {
      for (const hint of entry.code_hints ?? []) {
        if (hint.includes("*")) continue;
        if (!fs.existsSync(path.join(ctx.ws.root, hint))) {
          findings.push({ severity: "warn", rule: "design-code-drift", message: `${key}: code hint missing: ${hint}` });
        }
      }
    }
  }

  findings.push(...adapterDriftFindings(ctx.ws.root));
  return block(findings, ctx, findings.length ? `${findings.length} drift finding(s)` : "no drift detected");
};

/** integration-smoke: run integration test script when present (topology slot). */
export const integrationSmoke = (ctx: SensorContext): SensorReport => {
  const pkgFile = path.join(ctx.ws.root, "package.json");
  let scripts: Record<string, string> = {};
  if (fs.existsSync(pkgFile)) {
    try {
      scripts = (JSON.parse(fs.readFileSync(pkgFile, "utf8")) as { scripts?: Record<string, string> }).scripts ?? {};
    } catch {
      /* ignore */
    }
  }

  const hasIntegration = Boolean(scripts["test:integration"]);
  const candidates = ctx.def.run
    ? [ctx.def.run]
    : hasIntegration
      ? ["npm run test:integration"]
      : [];

  if (candidates.length === 0) {
    return {
      sensor: ctx.def.id,
      status: "pass",
      summary: "no integration test script found — skipped",
      findings: [{ severity: "info", message: "add npm run test:integration or set sensor run: override" }]
    };
  }

  for (const cmd of candidates) {
    const res = spawnSync(cmd, { shell: true, cwd: ctx.ws.root, encoding: "utf8", timeout: ctx.def.timeout_ms ?? 120_000 });
    if (res.error) continue;
    if (res.status === 0) {
      return { sensor: ctx.def.id, status: "pass", summary: "integration smoke passed", findings: [] };
    }
    return {
      sensor: ctx.def.id,
      status: "fail",
      summary: `integration smoke failed (exit ${res.status})`,
      findings: [{ severity: "block", message: (res.stderr || res.stdout || cmd).slice(0, 1500) }],
      fix_hint: ctx.def.fix_hint ?? "Fix integration tests"
    };
  }

  return { sensor: ctx.def.id, status: "error", summary: "integration smoke could not run", findings: [] };
};
