import fs from "node:fs";
import path from "node:path";
import { Workspace, ensureDir, sha256, PHASES } from "@harnessx/core";
import { computeTier, TARGETS, type Tier } from "./capability.js";

/**
 * T-604: single-source → multi-target compilation.
 * Sources are harnessX/assets/** (guides, commands via phase model); outputs
 * are native files per tool. Every generated file carries a header with the
 * adapter version and a content hash so manual edits are detectable.
 */

export const ADAPTER_VERSION = "1.0.0";

export interface CommandDef {
  name: string;
  description: string;
  run: string;
  /** Full phase workflow prompt (from guide.command assets); the agent-facing body of the slash command. */
  prompt?: string;
}

/** The standard hx command set, derived from the phase model (single source). */
export function standardCommands(): CommandDef[] {
  const map: Record<string, string> = {
    explore: "Read-only exploration; write findings to explore.md",
    propose: "Draft proposal.md + initial delta specs",
    design: "Write design.md (requires propose gate)",
    spec: "Refine delta specs; validate with spec-validate",
    plan: "Generate dual-track tasks.md",
    apply: "Implement task-by-task with fast-suite self-correction",
    verify: "Run the verification suite + traceability",
    archive: "Merge deltas into main specs and archive"
  };
  return PHASES.map((p) => ({
    name: `hx-${p.command}`,
    description: map[p.command] ?? p.display,
    run: `hx ${p.command === "explore" || p.command === "propose" ? `${p.command} <change>` : p.command === "archive" ? "archive <change>" : `${p.command} <change>`}`
  }));
}

/**
 * Standard commands enriched with the workspace's guide.command assets: for each
 * phase command, the matching guide.command source (harnessX/assets/commands/*)
 * becomes the slash-command prompt body. Missing assets fall back to the thin
 * description so compilation never breaks on a partial workspace.
 */
export function collectCommands(ws: Workspace): CommandDef[] {
  const harness = ws.readHarness();
  const commands = standardCommands();
  for (const g of harness.guides) {
    if (g.kind !== "guide.command") continue;
    const f = path.join(ws.base, g.source);
    if (!fs.existsSync(f)) continue;
    const content = fs.readFileSync(f, "utf8");
    for (const phase of g.phase) {
      const cmd = commands.find((c) => c.name === `hx-${phase}`);
      if (cmd) cmd.prompt = content;
    }
  }
  return commands;
}

/** Slash-command body: full workflow prompt when available, thin bridge otherwise. */
export function commandBody(c: CommandDef): string {
  if (c.prompt) return `${c.prompt.trimEnd()}\n\nCLI entry point: \`${c.run}\`\n`;
  return `# ${c.name}\n\n${c.description}\n\nRun:\n\n\`\`\`bash\n${c.run}\n\`\`\`\n`;
}

export interface SkillSource {
  id: string;
  content: string;
}

export function collectSkills(ws: Workspace): SkillSource[] {
  const harness = ws.readHarness();
  const out: SkillSource[] = [];
  for (const g of harness.guides) {
    if (g.kind !== "guide.skill") continue;
    const f = path.join(ws.base, g.source);
    if (fs.existsSync(f)) out.push({ id: g.id, content: fs.readFileSync(f, "utf8") });
  }
  return out;
}

export function rulesDigest(ws: Workspace): string {
  const parts: string[] = [];
  if (fs.existsSync(ws.constitutionFile)) {
    parts.push("## Constitution (highest priority)", fs.readFileSync(ws.constitutionFile, "utf8"));
  }
  parts.push(
    "## HarnessX ground rules",
    "- Work inside a change workspace; never edit harnessX/specs/ directly.",
    "- Never edit meta.yaml, harness.lock, fixtures.lock or approved fixtures by hand.",
    "- When a sensor fails, read fix_hint/agent_instruction before editing code.",
    "- Run `hx gate check <change>` before claiming a phase is complete."
  );
  return parts.join("\n\n");
}

/* ── generated file header + drift detection ── */

export function withHeader(content: string, sourceNote: string, commentStyle: "html" | "hash" = "html"): string {
  const hash = sha256(content).slice(0, 16);
  const line = `GENERATED by harnessx adapter v${ADAPTER_VERSION} from ${sourceNote} — do not edit (hash:${hash})`;
  return commentStyle === "html" ? `<!-- ${line} -->\n${content}` : `# ${line}\n${content}`;
}

const HEADER_RE = /GENERATED by harnessx adapter v([\d.]+) from (.+?) — do not edit \(hash:([0-9a-f]{16})\)/;

export type DriftState = "ok" | "manually-edited" | "missing-header";

/** Recomputes the body hash and compares with the header (T-604 手改检测). */
export function checkGeneratedFile(file: string): DriftState {
  const raw = fs.readFileSync(file, "utf8");
  const m = raw.match(HEADER_RE);
  if (!m) return "missing-header";
  const body = raw.split("\n").slice(1).join("\n");
  return sha256(body).slice(0, 16) === m[3] ? "ok" : "manually-edited";
}

export interface CompileResult {
  target: string;
  tier: Tier;
  files: string[];
  skipped: string[];
}

export type TargetEmitter = (ws: Workspace, ctx: EmitContext) => { files: string[]; skipped: string[] };

export interface EmitContext {
  commands: CommandDef[];
  skills: SkillSource[];
  rules: string;
  write: (rel: string, content: string, style?: "html" | "hash") => string;
}

export function makeEmitContext(ws: Workspace): Omit<EmitContext, "write"> {
  return { commands: collectCommands(ws), skills: collectSkills(ws), rules: rulesDigest(ws) };
}

export function compileTarget(ws: Workspace, target: string, emitter: TargetEmitter): CompileResult {
  const spec = TARGETS[target];
  if (!spec) throw new Error(`unknown adapter target: ${target}`);
  const files: string[] = [];
  const ctx: EmitContext = {
    ...makeEmitContext(ws),
    write: (rel, content, style = "html") => {
      const abs = path.join(ws.root, rel);
      ensureDir(path.dirname(abs));
      fs.writeFileSync(abs, withHeader(content, "harnessX/assets", style));
      files.push(rel);
      return rel;
    }
  };
  const res = emitter(ws, ctx);
  return { target, tier: computeTier(spec.capabilities), files: [...files, ...res.files], skipped: res.skipped };
}
